VEGA-2808, VEGA-2807: добавил максимальный размер для компонента Tree, пробросил…
gpn-prototypes/vega-rb pull request #44
Opened 2020-12-09 09:35 UTC by ronikjkee

… название проекта в структуру дерева, добавил фильтрацию по строкам при выборе элемента дерева

## Чек-лист

- [ ] Назначен исполнитель PR
- [ ] eslint/stylelint и dev-консоль браузера без ошибок
- [ ] Написаны тесты или заведена задача на покрытие тестами

## Дополнительно

- [ ] проверять все разрешения, когда меняется верстка
- [ ] Указан `no_test` лейбл в задаче, если не требуется тестирование QA
- [ ] В задаче описано, как тестировать изменения (если это нужно)

2020-12-09 22:35 UTC, d4rkm3z commented on src/pages/Scheme/components/TreeEditor/helpers.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Т.е. чтобы линтер просто так не ругался, ты его решил заглушить?

2020-12-09 22:55 UTC, d4rkm3z requested changes

2020-12-09 22:55 UTC, d4rkm3z commented on src/pages/Scheme/components/TreeEditor/helpers.ts
> +// eslint-disable-next-line consistent-return
И вот тут тоже.

2020-12-09 22:55 UTC, d4rkm3z commented on src/store/types.ts
> +  treeFilter: TreeFilterState;
На мой всзгляд лучше отталкиваться от абстракции дерева, а не от конкретной реализации фильтр. Если тебе потребуется потом добавлять что-то еще в стор с деревом, создашь еще один стор или добавишь в этот?

2020-12-09 22:55 UTC, d4rkm3z commented on src/pages/Scheme/components/TreeEditor/helpers.ts
> +  const parentId = isRoot
Добавь переносы строк пожалуйста между методами.

2020-12-09 22:55 UTC, d4rkm3z commented on src/pages/Scheme/components/Table/Table.tsx
> +            !structureColumnsKeys.some(({ key }) => key !== 'id' && row[key]),
Тебе самому хоть комфортно такой код читать?

2020-12-09 22:55 UTC, d4rkm3z commented on src/pages/Scheme/components/TreeEditor/TreeEditor.tsx
>            Дерево проекта
Все текстовые блоки надо оборачивать в компонент Text из консты

2020-12-09 22:55 UTC, d4rkm3z commented on src/pages/Scheme/Scheme.tsx
>  import TreeEditor from 'pages/Scheme/components/TreeEditor/TreeEditor';
Никогда такого не было и вот опять - тащи импорт из index компонета

2020-12-09 22:55 UTC, d4rkm3z commented on src/pages/Scheme/components/TreeEditor/helpers.ts
> +      nodeList: arrayToTree(nodes, {
Почему ты не захотел создавать переменную с этими значениями, а предпочел вложенность?

2020-12-09 22:56 UTC, d4rkm3z commented on src/pages/Scheme/components/TreeEditor/helpers.ts
>  import { get, groupBy, mergeWith } from 'lodash';
используй lodash/fp

2020-12-09 22:57 UTC, d4rkm3z commented on src/pages/Scheme/components/TreeEditor/helpers.ts
>  import { v4 as uuidv4 } from 'uuid';
лучше использовать uuid в качестве имени, если ты решишь изменить версию, не потребуется лазать по всему коду и вносить правки

2020-12-10 08:58 UTC, ronikjkee commented on src/pages/Scheme/components/TreeEditor/TreeEditor.tsx
>            Дерево проекта
done

2020-12-10 08:59 UTC, ronikjkee commented on src/pages/Scheme/Scheme.tsx
>  import TreeEditor from 'pages/Scheme/components/TreeEditor/TreeEditor';
done

2020-12-10 08:59 UTC, ronikjkee commented on src/pages/Scheme/components/TreeEditor/helpers.ts
> +      nodeList: arrayToTree(nodes, {
done

2020-12-10 08:59 UTC, ronikjkee commented on src/pages/Scheme/components/TreeEditor/helpers.ts
>  import { get, groupBy, mergeWith } from 'lodash';
done

2020-12-10 08:59 UTC, ronikjkee commented on src/pages/Scheme/components/TreeEditor/helpers.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
убрал

2020-12-10 08:59 UTC, ronikjkee commented on src/pages/Scheme/components/TreeEditor/helpers.ts
> +// eslint-disable-next-line consistent-return
убрал

2020-12-10 08:59 UTC, ronikjkee commented on src/store/types.ts
> +  treeFilter: TreeFilterState;
Исправил

2020-12-10 08:59 UTC, ronikjkee commented on src/pages/Scheme/components/TreeEditor/helpers.ts
> +  const parentId = isRoot
Добавил

2020-12-10 09:00 UTC, ronikjkee commented on src/pages/Scheme/components/Table/Table.tsx
> +            !structureColumnsKeys.some(({ key }) => key !== 'id' && row[key]),
Поправил

2020-12-10 10:18 UTC, ronikjkee commented on src/pages/Scheme/components/TreeEditor/helpers.ts
>  import { v4 as uuidv4 } from 'uuid';
Он сейчас используется в качестве id. Не думаю что это может вызвать какие либо трудности при рефакторинге

2020-12-10 10:45 UTC, d4rkm3z approved these changes

2020-12-11 10:10 UTC, merged