[Bug fix][VEGA-2988][VEGA-2995]: иправил ошибки при перемешении по проектам
gpn-prototypes/vega-rb pull request #83
Opened 2021-01-26 14:47 UTC by ronikjkee

### Description
   добавил хук useUnmount и экшен для сброса данных в таблицы
### Checks
- [x] Jira link attached: [VEGA-2988](https://jira.konakov.tv/browse/VEGA-2988), [VEGA-2995](https://jira.konakov.tv/browse/VEGA-2995)
- [ ] Possible Associated Jira links:
- [ ] Personal Vega Instance link attached: http://rlunev-nd-vega-builder.code013.org/
- [ ] Jira tasks for technical debt were created (if needed)
### Type
- [ ] Feature
- [ ] Alpha Feature ([Alpha] MR/PR Title)
- [x] Bug Fix
- [ ] Test
- [ ] Refactoring
### PR/MR Requirements
- [ ] PR/MR title meet requirements/convention
- [x] Target branch is correct
- [x] PR/MR branch was rebased at correct branch
- [x] Diff was checked
- [ ] Configuration files were checked at test repositories
- [ ] [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
### General
- [ ] Exploratory Tested at Personal Vega Instance
- [ ] Existing E2E Tests done, Screenshot attached
- [ ] Existing Integration Tests done, Screenshot attached, Jenkins link: 
- [ ] Existing Unit Tests done, Screenshot attached
- [ ] New E2E Tests developed 
- [ ] New Integration Tests developed
- [ ] New Unit Tests developed
- [ ] API documentation was fully and correctly updated
### Integration Tests Screenshot
   _{Screenshot}_
### Unit Tests Screenshot
   _{Screenshot}_

2021-02-09 14:45 UTC, d4rkm3z approved these changes

2021-02-09 21:30 UTC, victorusachev approved these changes

2021-02-10 14:29 UTC, Davs777 approved these changes

2021-02-15 15:44 UTC, ronikjkee commented
@d4rkm3z , @victorusachev , Нужно обсудить этот фикс. Каким образом лучше исправить эти баги?

2021-02-20 12:58 UTC, d4rkm3z requested changes

2021-02-20 12:58 UTC, d4rkm3z commented on src/pages/Scheme/components/CalculateButton/CalculateButton.tsx
> +                id: projectId,
А нам разве недоступен id проекта в редюсере ошибок?

2021-02-24 08:00 UTC, ronikjkee commented on src/pages/Scheme/components/CalculateButton/CalculateButton.tsx
> +                id: projectId,
Недоступен. При обновлении стейта мы должны пробрасывать id для сохранения/обновления ошибок.

2021-02-24 08:05 UTC, ronikjkee commented on src/components/TableErrorAlert/TableErrorAlert.tsx
> +  );
Использовал хук

2021-02-24 08:26 UTC, ronikjkee commented on src/hooks/useUpdateErrors.ts
> +  const errors = useSelector(({ errors: errorsState }: RootState) =>
Использовал хук

2021-02-24 08:28 UTC, ronikjkee commented on src/store/tableErrorsDuck.ts
> +    ofAction(tableDuck.actions.updateCell),
Перенес эпик в tableDuck.

2021-02-24 08:54 UTC, ronikjkee commented on src/hooks/useGetError.ts
> +  path?: PropertyPath,
Избавился от импорта

2021-03-01 13:26 UTC, ronikjkee commented on src/__mocks__/errorsState.ts
> +  ids: ['project_0001'],
@victorusachev, в тестах и сторибуке

2021-03-01 13:28 UTC, d4rkm3z approved these changes

2021-03-01 13:28 UTC, victorusachev approved these changes

2021-03-01 14:17 UTC, merged