[VEGA-3172]: добавить усечение мин/макс для распределений
gpn-prototypes/vega-rb pull request #92
Opened 2021-02-15 15:19 UTC by ronikjkee

### Description
добавить усечение мин/макс для распределений

### Checks
- [ ] Jira link attached: [VEGA-3172](https://jira.vegaspace.tk/browse/VEGA-3172)
- [ ] Possible Associated Jira links:
- [ ] Personal Vega Instance link attached: http://xx-yy-vega-builder.code013.org
- [ ] Jira tasks for technical debt were created (if needed)

### Type
- [ ] Feature
- [ ] Alpha Feature ([Alpha] MR/PR Title)
- [ ] Bug Fix
- [ ] Test
- [ ] Refactoring

### PR/MR Requirements
- [ ] PR/MR title meet requirements/convention
- [ ] Target branch is correct
- [ ] PR/MR branch was rebased at correct branch
- [ ] Diff was checked
- [ ] Configuration files were checked at test repositories
- [ ] [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

### General
- [ ] Exploratory Tested at Personal Vega Instance
- [ ] Existing E2E Tests done, Screenshot attached
- [ ] Existing Integration Tests done, Screenshot attached, Jenkins link:
- [ ] Existing Unit Tests done, Screenshot attached
- [ ] New E2E Tests developed
- [ ] New Integration Tests developed
- [ ] New Unit Tests developed
- [ ] API documentation was fully and correctly updated

### E2E Suite Jenkins link
_{link}_

### E2E Suite Screenshot
_{Screenshot}_

### Integration Tests Screenshot
_{Screenshot}_

### Unit Tests Screenshot
_{Screenshot}_

2021-02-18 00:55 UTC, d4rkm3z requested changes

2021-02-18 00:55 UTC, d4rkm3z commented on src/components/DistributionSettings/helpers.ts
> +    (Object.keys(parameters) as DistributionParameterTypes[]).every((key) =>
Предполагаю, что всю эту функцию возможно сократить до 

```typescript
import { every } from 'lodash/fp';

export const validateDistributionParams = ({
  parameters,
  minBound = 0,
  maxBound = 0,
}: DistributionSettingsFormData): boolean => {
  return every(isNumeric, { ...parameters, minBound, maxBound });
}
```

2021-02-18 13:55 UTC, ronikjkee commented on src/components/DistributionSettings/DistributionSettings.tsx
> +        const isValid = validateDistributionParams(
В result еще есть параметры distributionType и distributionDefinitionType. Поэтому в этом случае лучше оставить так.

2021-02-18 14:42 UTC, ronikjkee commented on src/components/DistributionSettings/helpers.ts
> +    (Object.keys(parameters) as DistributionParameterTypes[]).every((key) =>
Поправил исходя из логики заполнения формы(в твоем случае форма не рендерит график если параметры minBound или maxBound не заполненны т.к интпут возвращает null)

2021-02-18 14:42 UTC, ronikjkee commented on src/components/DistributionSettings/DistributionSettingsForm/DistributionSettingsForm.tsx
> +  // eslint-disable-next-line
убрал

2021-02-18 15:30 UTC, d4rkm3z commented on src/components/DistributionSettings/DistributionSettings.tsx
> +        const isValid = validateDistributionParams(
Если в функции используются только те параметры, какие необходимы, то наличие distributionType и distributionDefinitionType не играет роли

2021-02-18 15:34 UTC, d4rkm3z commented on src/components/DistributionSettings/helpers.ts
> +    (Object.keys(parameters) as DistributionParameterTypes[]).every((key) =>
В твоем решении, если minBound и maxBound не инициализированы, то ты возвращаешь true, через отрицание. В моем случае тот же самый механизм происходит при задании значения по-умолчанию равному 0.

2021-02-18 15:44 UTC, d4rkm3z commented on src/components/DistributionSettings/helpers.ts
> +    (Object.keys(parameters) as DistributionParameterTypes[]).every((key) =>
Нет необходимости вызова Object.values, т.к. every из lodash сам передает в обработчик values

2021-02-18 23:00 UTC, victorusachev requested changes

2021-02-18 23:00 UTC, victorusachev commented on src/components/DistributionSettings/DistributionSettingsForm/DistributionSettingsForm.tsx
> +            value={formData.minBound?.toString() || ''}
Что уйдёт на сервер, если здесь будет `''`? Пустая строка, 0 или null?

2021-02-18 23:00 UTC, victorusachev commented on src/components/DistributionSettings/DistributionSettingsForm/DistributionSettingsForm.tsx
> +            value={formData.minBound?.toString() || ''}
Откуда берётся значение по умолчанию?

2021-02-18 23:00 UTC, victorusachev commented on src/components/DistributionSettings/DistributionSettingsForm/DistributionSettingsForm.tsx
> +            label={<Form.Label>Min</Form.Label>}
Min -> Мин. значение

2021-02-18 23:00 UTC, victorusachev commented on src/components/DistributionSettings/DistributionSettingsForm/DistributionSettingsForm.tsx
> +            label={<Form.Label>Max</Form.Label>}
Max -> Макс. значение

2021-02-18 23:00 UTC, victorusachev commented on src/components/DistributionSettings/DistributionSettingsForm/DistributionSettingsForm.tsx
> +            value={formData.maxBound?.toString() || ''}
Те же вопросы: откуда значение по умолчанию и какое значение уйдёт на сервер, если здесь будет пустая строка?

2021-02-18 23:00 UTC, victorusachev commented on src/components/DistributionSettings/types.ts
> +  minBound?: string;
Кстати, почему `string`?

2021-02-19 07:27 UTC, ronikjkee commented on src/components/DistributionSettings/DistributionSettings.tsx
> +        const isValid = validateDistributionParams(
Исправил

2021-02-19 07:38 UTC, ronikjkee commented on src/components/DistributionSettings/helpers.ts
> +    (Object.keys(parameters) as DistributionParameterTypes[]).every((key) =>
В случае если они не проиницилизированны и данные ушли на бэк без задания границ, то при запросе данных с бэкенда на вернется minBound:null и maxBound: null, сдедовательно в цикл every попадут minBound = null и maxBound = null, а не 0 и 0, поэтому график перестанет отображаться т.к уловие валидации не позволит отправить запрос на бэк.

2021-02-19 07:38 UTC, ronikjkee commented on src/components/DistributionSettings/helpers.ts
> +    (Object.keys(parameters) as DistributionParameterTypes[]).every((key) =>
Убрал Object.values

2021-02-19 07:46 UTC, ronikjkee commented on src/components/DistributionSettings/DistributionSettingsForm/DistributionSettingsForm.tsx
> +            value={formData.maxBound?.toString() || ''}
если значения пустые то на сервер уйдут данные: 
![image](https://user-images.githubusercontent.com/18334403/108473961-c1b28200-729f-11eb-892b-058e0ac793c4.png)

2021-02-19 07:47 UTC, ronikjkee commented on src/components/DistributionSettings/DistributionSettingsForm/DistributionSettingsForm.tsx
> +            value={formData.minBound?.toString() || ''}
Исправил тип

2021-02-19 07:48 UTC, ronikjkee commented on src/components/DistributionSettings/DistributionSettingsForm/DistributionSettingsForm.tsx
> +            label={<Form.Label>Max</Form.Label>}
Исправил

2021-02-19 07:48 UTC, ronikjkee commented on src/components/DistributionSettings/DistributionSettingsForm/DistributionSettingsForm.tsx
> +            label={<Form.Label>Min</Form.Label>}
Исправи

2021-02-19 07:48 UTC, ronikjkee commented on src/components/DistributionSettings/types.ts
> +  minBound?: string;
Изменил на number

2021-02-19 09:59 UTC, d4rkm3z approved these changes

2021-02-19 10:07 UTC, ronikjkee commented on src/components/DistributionSettings/DistributionSettingsForm/DistributionSettingsForm.tsx
> +            value={formData.minBound?.toString() || ''}
есть валидация и на сервер будут отправлены числовые значения > 0

2021-02-19 13:38 UTC, victorusachev approved these changes

2021-02-19 13:40 UTC, merged