chore(react-data-grid): обновил версию react-data-grid
gpn-prototypes/vega-rb pull request #94
Opened 2021-02-20 11:25 UTC by ronikjkee

### Description
Обновил версию react-data-grid
Поправил стили таблицы
Переписал обработчики и типы

### Checks
- [x] Jira link attached: [VEGA-2916](https://jira.konakov.tv/browse/VEGA-2916) [VEGA-2912](https://jira.konakov.tv/browse/VEGA-2912) [VEGA-2985](https://jira.konakov.tv/browse/VEGA-2985) [VEGA-2989](https://jira.konakov.tv/browse/VEGA-2989)
- [ ] Possible Associated Jira links:
- [x] Personal Vega Instance link attached: http://rlunev-nedra-vega-builder.code013.org/
- [ ] Jira tasks for technical debt were created (if needed)

### Type
- [ ] Feature
- [ ] Alpha Feature ([Alpha] MR/PR Title)
- [x] Bug Fix
- [ ] Test
- [x] Refactoring

### PR/MR Requirements
- [x] PR/MR title meet requirements/convention
- [x] Target branch is correct
- [x] PR/MR branch was rebased at correct branch
- [x] Diff was checked
- [ ] Configuration files were checked at test repositories
- [x] [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

### General
- [ ] Exploratory Tested at Personal Vega Instance
- [ ] Existing E2E Tests done, Screenshot attached
- [ ] Existing Integration Tests done, Screenshot attached, Jenkins link:
- [ ] Existing Unit Tests done, Screenshot attached
- [ ] New E2E Tests developed
- [ ] New Integration Tests developed
- [ ] New Unit Tests developed
- [ ] API documentation was fully and correctly updated

### E2E Suite Jenkins link
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/201/

### E2E Suite Screenshot
_{Screenshot}_

2021-03-02 10:35 UTC, d4rkm3z requested changes

2021-03-02 15:22 UTC, ronikjkee commented on src/components/ExcelTable/Editors/DropDownEditor/DropDownEditor.tsx
> +            onClick={() =>
done

2021-03-02 15:22 UTC, ronikjkee commented on src/components/ExcelTable/Editors/SimpleTextEditor.tsx
> +    <>
fixed

2021-03-02 15:23 UTC, ronikjkee commented on src/components/ExcelTable/Editors/SimpleTextEditor.tsx
> +      | React.ChangeEvent<HTMLInputElement>
вынес

2021-03-02 15:24 UTC, ronikjkee commented on src/components/HierarchyLevelList/HierarchyLevelList.tsx
> +                  name={item.name as string}
string

2021-03-02 15:24 UTC, ronikjkee commented on src/components/HierarchyLevelList/HierarchyLevelList.tsx
> +                  name={item.name as string}
убрал

2021-03-02 15:24 UTC, ronikjkee commented on src/components/ExcelTable/ExcelTable.tsx
> +    const riskColumns = getColumnsByType(data.columns, TableEntities.RISK);
исправил

2021-03-02 15:26 UTC, ronikjkee commented on src/pages/Scheme/components/Table/Table.tsx
> +      setRows={(data, indexes): void => {
Не вижу смысла разделять на функции в этом случае. Вынес все функции из jsx.

2021-03-02 15:27 UTC, ronikjkee commented on src/components/ExcelTable/Editors/SimpleTextEditor.tsx
> +export const SimpleTextEditor: React.FC<EditorProps<GridRow | undefined>> = ({
Вернул тип

2021-03-02 15:35 UTC, d4rkm3z commented on src/components/ExcelTable/Editors/SimpleTextEditor.tsx
> +type ChangeEvent =
```
import React, { ChangeEvent, FocusEvent } from 'react';

type EditorChangeEvent<T> = ChangeEvent<T> | FocusEvent<T>

const handleChange = (event: EditorChangeEvent<HTMLInputElement >) {
}
```

2021-03-02 15:52 UTC, ronikjkee commented on src/components/ExcelTable/ExcelTable.css
> +  background: rgba(0, 0, 255, 0.2);
в ui-kit нету такого цвета т.к его нету в макетах.

2021-03-02 15:53 UTC, ronikjkee commented on src/components/ExcelTable/ExcelTable.css
> +.ExcelTable .rdg-text-editor {
Поправил

2021-03-02 16:09 UTC, ronikjkee commented on src/components/ExcelTable/Header/DefaultHeader/DefaultHeader.tsx
> +      column={props.column}
Почистил

2021-03-02 16:12 UTC, ronikjkee commented on src/components/ExcelTable/Editors/SimpleTextEditor.tsx
> +type ChangeEvent =
done

2021-03-11 20:24 UTC, d4rkm3z commented on src/components/ExcelTable/Editors/SimpleTextEditor.tsx
> +  };
Добавь пожалуйста перенос строки, для визуального разделения

2021-03-11 20:24 UTC, d4rkm3z commented on src/components/ExcelTable/Editors/DropDownEditor/DropDownEditor.tsx
> +export default DropDownEditor;
Разве нам не нужен forwardRef? Если извне где-то использовался ref из этого компонента, то он не будет работать.

2021-03-11 20:24 UTC, d4rkm3z commented on src/components/ExcelTable/Cells/CellWithError.tsx
> +  const selectCellWrapper = (openEditor?: boolean) => {
Переименуй на shouldOpenEditor, это больше подходит по смыслу для булевых переменных

2021-03-11 20:24 UTC, d4rkm3z commented on src/components/ExcelTable/Cells/DropDownCell/DropDownCell.tsx
> +    // left: column.left,
Если не нужно, удали

2021-03-11 20:24 UTC, d4rkm3z commented on src/pages/Scheme/components/Table/Table.tsx
> +    rowIdx: number;
Вынеси пожалуйста в отдельный тип весь этот блок

2021-03-11 20:24 UTC, d4rkm3z commented on src/pages/Scheme/components/Table/Table.tsx
> +  const handleSetRows = (
На мой взгляд стоит разбить эту функцию на мелкие, по-крайней мере можно вынести newRows

2021-03-11 20:24 UTC, d4rkm3z commented on src/pages/Scheme/components/Table/Table.tsx
> +    const rowIsFulfilled = (row: GridRow): boolean =>
Возможно м можем вынести эту функцию, модифицировав ее в чистую функцию

2021-03-11 20:24 UTC, d4rkm3z commented on src/pages/Scheme/components/Table/Table.tsx
> +        const columnKeys = treeFilterData.columns;
Полагаю мы можем определить эту константу намного раньше, чтобы убрать использование treeFilterData.columns, а так же сделать это с treeFilterData.rows или нет?

2021-03-11 20:24 UTC, d4rkm3z commented on src/pages/Scheme/components/Table/Table.tsx
> +      // TODO: to remove pass column objet
Думаю мы так никогда и не дойдем до этого туду, может удалим его? Или думаешь, что все же пригодится?

2021-03-12 09:58 UTC, ronikjkee commented on src/components/HierarchyLevelList/HierarchyLevelList.tsx
> +                  name={item.name as string}
done

2021-03-12 09:58 UTC, ronikjkee commented on src/components/ExcelTable/types.ts
> +  | {
done

2021-03-12 10:00 UTC, ronikjkee commented on src/components/ExcelTable/ExcelTable.css
> +  .ExcelTable__Header {
Нужен уровень вложенности для увеличения веса, чтобы стили таблицы были переопределены(css in js)

2021-03-12 10:00 UTC, ronikjkee commented on src/components/ExcelTable/Editors/SimpleTextEditor.tsx
> +  };
готово

2021-03-12 10:01 UTC, ronikjkee commented on src/components/ExcelTable/Header/DraggableHeader/DraggableHeader.tsx
> +import { HeaderRendererProps } from 'react-data-grid';
Проблем с использованием этого типа не заметил

2021-03-12 10:01 UTC, ronikjkee commented on src/pages/Scheme/components/Table/Table.tsx
> +    rowIdx: number;
Вынес

2021-03-12 10:03 UTC, ronikjkee commented on src/pages/Scheme/components/Table/Table.tsx
> +    const rowIsFulfilled = (row: GridRow): boolean =>
Вынес функцию

2021-03-12 10:03 UTC, ronikjkee commented on src/pages/Scheme/components/Table/Table.tsx
> +        const columnKeys = treeFilterData.columns;
Перенес

2021-03-12 10:03 UTC, ronikjkee commented on src/pages/Scheme/components/Table/Table.tsx
> +      // TODO: to remove pass column objet
Убрал

2021-03-12 10:05 UTC, ronikjkee commented on src/pages/Scheme/components/Table/Table.tsx
> +  const handleSetRows = (
Слишком много зависимостей внутри этой функции. Не знаю стоит ли пытаться разбить её

2021-03-12 10:14 UTC, d4rkm3z commented on src/pages/Scheme/components/Table/Table.tsx
> +      setRows={(data, indexes): void => {
Чем больше функция - тем она менее понятна и выше риск ее поломки

2021-03-12 10:55 UTC, ronikjkee commented on src/components/ExcelTable/Editors/DropDownEditor/DropDownEditor.tsx
> +export default DropDownEditor;
forwardRef не используется на данный момент

2021-03-12 10:55 UTC, ronikjkee commented on src/components/ExcelTable/Cells/CellWithError.tsx
> +  const selectCellWrapper = (openEditor?: boolean) => {
done

2021-03-12 10:55 UTC, ronikjkee commented on src/components/ExcelTable/Cells/DropDownCell/DropDownCell.tsx
> +    // left: column.left,
удалил

2021-03-12 14:07 UTC, d4rkm3z approved these changes

2021-03-12 14:30 UTC, victorusachev approved these changes

2021-03-12 14:51 UTC, victorusachev approved these changes

2021-03-12 15:47 UTC, merged